language: julia
os:
  - osx
  - linux
julia:
  - 1.1
notifications:
  email: false
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'Pkg.clone(pwd());'
#   - julia -e 'ENV["MADS_TRAVIS"]=""; Pkg.build("GeostatInversion"); Pkg.test("GeostatInversion"; coverage=true)'
after_success:
  - julia -e 'import GeostatInversion; joinpath(dirname(pathof(GeostatInversion)); Pkg.add("Coverage"); import Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
